### ISSUE TITLE
ostest fails on invalid (expired) GPG key for apt.puppetlabs.com 

### ISSUE THREAD

**Issue by snesbittsea** [example42/psick#108]
Ostest fail as follows:
 
ubuntu1604.ostest.psick.io:
 Error: /Stage[main]/Puppet::Profile::Agent/Tp::Install[puppet-agent]/Tp::Repo[puppet-agent]/Exec[tp_apt_update]: Failed to call refresh: /usr/bin/apt-get -qq update returned 100 instead of one of [0]

running `/usr/bin/apt-get -qq update` results in:

ubuntu@ubuntu1604:~$ sudo /usr/bin/apt-get -qq update
 
W: http://apt.puppetlabs.com/dists/stable/Release.gpg: Signature by key 47B320EB4C7C375AA9DAE1A01054B7A24BD6EC30 uses weak digest algorithm (SHA1)
W: GPG error: http://apt.puppetlabs.com stable Release: The following signatures were invalid: KEYEXPIRED 1483574797
W: The repository 'http://apt.puppetlabs.com stable Release' is not signed.
W: Invalid 'Date' entry in Release file /var/lib/apt/lists/partial/apt.puppetlabs.com_dists_stable_Release
E: Failed to fetch http://apt.puppetlabs.com/dists/stable/PC1/binary-amd64/Packages  404  Not Found [IP: 192.155.89.90 80]
E: Some index files failed to download. They have been ignored, or old ones used instead.`

**Comment by alvagante** [comment]
Great catch.
I just realised that the in module tinydata of the puppet module used on Psick was not updated.
This commit fixes the problem:
https://github.com/example42/puppet-puppet/commit/6257956824b7a496f90e282a8b3ae546cfc736b5

note that you'll need to update the 4.x branch of the puppet-puppet module in order to get new code (version 4 of the module is still not on Master, but will be soon)
