### ISSUE TITLE
Root requirements for setup (revisited)

### ISSUE THREAD

**Issue by snesbittsea** [example42/psick#110]
I maybe missing something or misunderstanding the workflow for psick. If so I apologize and would welcome enlightenment !

As I feared, I did run into an apparent issue in my development environment evidently caused by needing to run too much of the psick setup process as root. 

Scenario:
- A development environment on my local development machine owned by a local user account.
- Environment configured to use rvm in order to isolate development from system ruby configuration => most commands in development area are run using bundler.
- A need (or at least I think so) to run `r10k puppetfile install` in order to update existing module dependencies (new dependencies, new versions, remove obsolete)

Issues:
- `bundle exec r10k puppetfile install` fails because r10k gem not found. That's because psick setup installed it at the system level (or so I believe).
- After adding r10k to my Gemfile and performing a `bundle install`, `bundle exec r10k puppetfile install` fails to update most modules because of Permission Denied errors. It turns out that the currently installed modules are owned by root and I am running the command as my local development user. Again I suspect that the root ownership is the result of the psick setup process which was run as root.

In my opinion, a local development environment that requires root access for normal development activities and that depends on packages installed at the system level is not a good thing. :-)

Am I missing some aspect of Psick workflow that would address these concerns? Can/should  Psick setup be refactored to limit what needs to be installed at the system level and to support a rvm environment?

Hope I'm not barking up the wrong tree.

-steve

**Comment by alvagante** [comment]
Hi, thanks for the feedback from the real world, as it's useful to cope with cases we hadn't well documented or just considered.

So, on development station (and actually everywhere) psick should be run as normal user.
Root privileges are needed only for certain setup commands which are there only to make it easier (?) to install the needed prerequisites (which means that you don't have to run them if you install the needed packages/gems by yourself).

Scripts actually install gem using puppet package type, and they do that at system level, so actually, as you noted,  you probably need to install them manually for your local rvm environment.
I should review the setup from scratch based on the current docs, to see if everything runs fines for different use cases, I'm going to eventually close this issue when done.

As for root permissions issues check if the modules directory, inside the psick dir, is owner by root.
If should not be, and if it is it's probably because you previously run as root either r10k or the puppet_setup.sh script (which runs r10k).
Note also that you should run r10k puppetfile install [-v] from the main psick directory, where the same Puppetfile is present and under which the modules dir is supposed to be created.

This looks like, mostly a documentation or a setup scrupts issue, which should be revised to behave well under rvm/rbenv and normal systems.
What's important to understand around this, anyway, is that the setup scripts (which are the only ones requiring root privileges) just (try to) install the needed prerequisites (which can be installed in other ways) and run r10k puppetfile install (which you can directly). Nothing more, if you have the relevant dependencies satisfied you can just ignore them.

**Comment by snesbittsea** [comment]
Ok, it's beginning to make sense. I'll wipe my existing environment and
reinstall based on your notes here.

Two questions:

   1. Under Psick what is the intended means for managing
   dependencies/modules? R10K or librarian-puppet? In the past I've used R10K
   for puppet masters and puppet agents, but librarian-puppet for development.
   2. Is there a wiki setup where  I could add recipes such as "Setting up
   a local development environment". Or maybe add a documentation directory to
   which recipes can be added?


Thanks again!

-steve

**Comment by alvagante** [comment]
I've always used r10k with psick (note, always using the the command ```r10k puppetfile install``` to install modules directly in the modules dir in psick dir (and not on system's module dir)  but librarian-puppet should work the same. 
For both the cases, the point is to have the needed modules defined in Puppetfile available in the modules dir , you could git clone them one by one manually and that  would be ok too.

In the docs directory should be placed additional tutorials, docs and use cases. Give them a read, if you haven't done yet, they can be useful to find out more about more ore less hidden features of psick

**Comment by alvagante** [comment]
@snesbittsea please reopen or open a new ticket if you think the linked commit is not enough :-)
